image: php:8.1.0-fpm

pipelines:
  default:
   - step:
      name: Setup Environment
      script:
        - apt-get update && apt-get install -y unzip
        - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
        - composer install
        - apt-get --assume-yes install git-core
        - git --version
        - git clone git@bitbucket.org:jvuzzell/environment_config.git environment_variables
        - pwd 
        - ls
        - ls environment_variables
        - cd protools_framework/bootstrap/testing/
        - php index.php testing.prototypes.dv/testing
        - cat /opt/atlassian/pipelines/agent/build/protools_framework/tests/test-results/20221002_094532_testing-the-test-framework.xml

