# Template PHP Build

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

image: php:8.1.0-fpm


pipelines:
  default:
      - step:
          name: Install Composer
          caches: 
            - composer-bin-cache
          script:
            - php --version
            - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            - php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            - php composer-setup.php
            - php -r "unlink('composer-setup.php');"
            - mv composer.phar /usr/local/bin/composer
            
      - step: 
          name: Install ProTools Dependencies 
          script: 
            - pwd
            - composer install

definitions:
  caches:
    composer-bin-cache: /usr/local/bin/composer