<?php 

return array(
    'prod' => array(
        'url' => array(
            'main_site' => '', 
            'static_assets' => '', 
            'testing' => '', 
            'builder' => '', 
            'cms' => '',
            'api' => '', 
        )
    ),
    'staging' => array(
        'url' => array(
            'main_site' => '', 
            'static_assets' => '', 
            'testing' => '', 
            'builder' => '', 
            'cms' => '',
            'api' => '', 
        )
    ),
    'uat' => array(
        'url' => array(
            'main_site' => '', 
            'static_assets' => '', 
            'testing' => '', 
            'builder' => '', 
            'cms' => '',
            'api' => '', 
        )
    ),
    'qa' => array(
        'url' => array(
            'main_site' => '', 
            'static_assets' => '', 
            'testing' => '', 
            'builder' => '', 
            'cms' => '',
            'api' => '', 
        )
    ),
    'deployment' => array(
        'url' => array(
            'main_site' => 'prototypes.dv', 
            'static_assets' => 'assets.prototypes.dv', 
            'testing' => 'testing.prototypes.dv', 
            'builder' => 'builder.prototypes.dv', 
            'cms' => 'cms.prototypes.dv',
            'api' => 'api.prototypes.dv', 
        )
    ),
    'dev' => array(
        'url' => array(
            'main_site' => 'prototypes.dv', 
            'static_assets' => 'assets.prototypes.dv', 
            'testing' => 'testing.prototypes.dv', 
            'builder' => 'builder.prototypes.dv', 
            'cms' => 'cms.prototypes.dv',
            'api' => 'api.prototypes.dv', 
        )
    ),
);